/**
 * MercadoPago Mobile Payment Service
 * Handles payment flow integration for Tifossi Expo
 */

import * as WebBrowser from 'expo-web-browser';
import { endpoints } from '../../_config/endpoints';
import { deviceFingerprintService } from '../device/fingerprint';

export interface OrderData {
  id?: string;
  orderNumber?: string; // Generated by backend, optional from client
  items: OrderItem[];
  user: UserData;
  shippingAddress?: ShippingAddress | null; // Optional for pickup orders
  shippingMethod: 'delivery' | 'pickup';
  shippingCost: number;
  subtotal: number;
  discount?: number;
  total: number;
}

export interface OrderItem {
  productId: string;
  productName: string;
  description?: string;
  quantity: number;
  price: number;
  size?: string;
  color?: string;
}

export interface UserData {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: {
    areaCode?: string;
    number: string;
  };
  identification?: {
    type: 'CI' | 'CE' | 'RUT';
    number: string;
  };
}

export interface ShippingAddress {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state?: string;
  country: string;
  postalCode?: string;
}

export interface PaymentPreference {
  id: string;
  initPoint: string;
  externalReference: string;
}

export interface PaymentResult {
  success: boolean;
  orderId?: string;
  paymentId?: string;
  collectionId?: string;
  status?: 'approved' | 'rejected' | 'pending';
  error?: string;
  /** True when user dismissed browser without completing payment flow */
  userDismissed?: boolean;
}

export interface PaymentStatus {
  orderId: string;
  orderNumber: string;
  status: string;
  paymentInfo?: {
    id: string;
    status: string;
    statusDetail: string;
    amount: number;
    currency: string;
    paymentMethod: string;
    dateCreated: string;
    dateApproved?: string;
  };
}

class MercadoPagoService {
  private baseUrl: string;
  private authToken: string | null = null;

  constructor() {
    // Get base URL from centralized configuration
    this.baseUrl = endpoints.baseUrl;
  }

  /**
   * Set authentication token
   */
  setAuthToken(token: string) {
    this.authToken = token;
  }

  /**
   * Check if user data represents a guest user
   */
  private isGuestUser(userData: UserData): boolean {
    return typeof userData.id === 'string' && userData.id.startsWith('guest-');
  }

  /**
   * Create payment preference for an order
   */
  async createPaymentPreference(orderData: OrderData): Promise<PaymentPreference> {
    try {
      const isGuest = this.isGuestUser(orderData.user);

      // Only require auth for non-guest orders
      if (!isGuest && !this.authToken) {
        throw new Error('Authentication required');
      }

      // Get device fingerprint for fraud prevention
      const deviceFingerprint = await deviceFingerprintService.getDeviceFingerprint();

      if (isGuest) {
        // Use guest endpoint for unauthenticated users
        const guestOrderData = {
          ...orderData,
          guestEmail: orderData.user.email,
          guestName: `${orderData.user.firstName} ${orderData.user.lastName}`.trim(),
          guestPhone: orderData.user.phone?.number,
        };

        const url = `${this.baseUrl}/api/payment/guest/create-preference`;
        if (__DEV__) {
          console.log('[MercadoPago] Guest request URL:', url);
          console.log('[MercadoPago] Guest request data:', JSON.stringify(guestOrderData, null, 2));
        }

        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            orderData: guestOrderData,
            deviceFingerprint,
          }),
        });

        if (!response.ok) {
          const responseText = await response.text();
          let errorMessage = `HTTP ${response.status}`;
          try {
            const errorData = JSON.parse(responseText);
            errorMessage = errorData.error?.message || errorData.message || errorMessage;
          } catch {
            // Response wasn't JSON, use text or status
            if (responseText.length < 200) errorMessage = responseText || errorMessage;
          }
          console.error('[MercadoPago] Guest API error:', response.status, errorMessage);
          throw new Error(errorMessage);
        }

        const result = await response.json();
        if (__DEV__) {
          console.log('[MercadoPago] Guest response:', JSON.stringify(result, null, 2));
        }

        if (!result.success || !result.data) {
          throw new Error('Invalid response format from server');
        }

        return {
          id: result.data.preference.id,
          initPoint: result.data.preference.initPoint,
          externalReference: result.data.preference.externalReference,
        };
      }

      // Use authenticated endpoint for logged-in users
      const url = `${this.baseUrl}/api/payment/create-preference`;
      if (__DEV__) {
        console.log('[MercadoPago] Auth request URL:', url);
        console.log('[MercadoPago] Auth request data:', JSON.stringify(orderData, null, 2));
      }

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.authToken}`,
        },
        body: JSON.stringify({
          orderData,
          deviceFingerprint,
        }),
      });

      if (!response.ok) {
        const responseText = await response.text();
        let errorMessage = `HTTP ${response.status}`;
        try {
          const errorData = JSON.parse(responseText);
          errorMessage = errorData.error?.message || errorData.message || errorMessage;
        } catch {
          // Response wasn't JSON, use text or status
          if (responseText.length < 200) errorMessage = responseText || errorMessage;
        }
        console.error('[MercadoPago] Auth API error:', response.status, errorMessage);
        throw new Error(errorMessage);
      }

      const result = await response.json();
      if (__DEV__) {
        console.log('[MercadoPago] Auth response:', JSON.stringify(result, null, 2));
      }

      if (!result.success || !result.data) {
        throw new Error('Invalid response format from server');
      }

      return {
        id: result.data.preference.id,
        initPoint: result.data.preference.initPoint,
        externalReference: result.data.preference.externalReference,
      };
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      console.error('[MercadoPago] createPaymentPreference failed:', msg);
      throw new Error(msg);
    }
  }

  /**
   * Open payment flow using WebBrowser.openAuthSessionAsync
   *
   * Uses ASWebAuthenticationSession (iOS) / Custom Tabs (Android) which properly
   * handles redirects back to the app via custom URL schemes.
   *
   * Payment success is determined by:
   * 1. Redirect URL parameters (primary - from openAuthSessionAsync result)
   * 2. MercadoPago webhook notifications (backup)
   * 3. Polling the order status via API (fallback)
   */
  async initiatePayment(preference: PaymentPreference): Promise<PaymentResult> {
    try {
      // Define the redirect URL scheme that the auth session will listen for
      const redirectScheme = 'tifossi';

      // Open MercadoPago payment page using auth session
      // This properly handles the redirect back to the app
      const result = await WebBrowser.openAuthSessionAsync(preference.initPoint, redirectScheme);

      // Handle the result
      if (result.type === 'success' && result.url) {
        // Parse the redirect URL to extract payment status
        try {
          const url = new URL(result.url);
          const params = url.searchParams;

          // Check for payment status flags from our redirect endpoint
          if (params.get('paymentSuccess') === 'true') {
            return {
              success: true,
              orderId: preference.externalReference,
              paymentId: params.get('payment_id') || undefined,
              status: 'approved',
            };
          } else if (params.get('paymentFailure') === 'true') {
            return {
              success: false,
              orderId: preference.externalReference,
              status: 'rejected',
              error: 'Payment was rejected',
            };
          } else if (params.get('paymentPending') === 'true') {
            return {
              success: true,
              orderId: preference.externalReference,
              status: 'pending',
            };
          }

          // If no explicit status, return pending for verification
          return {
            success: true,
            orderId: params.get('external_reference') || preference.externalReference,
            status: 'pending',
          };
        } catch {
          // URL parsing failed, return pending for verification
          return {
            success: true,
            orderId: preference.externalReference,
            status: 'pending',
          };
        }
      }

      // User cancelled or dismissed without completing redirect flow
      if (result.type === 'cancel' || result.type === 'dismiss') {
        return {
          success: true,
          orderId: preference.externalReference,
          status: 'pending',
          userDismissed: true,
        };
      }

      return {
        success: true,
        orderId: preference.externalReference,
        status: 'pending',
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'No se pudo abrir la página de pago',
      };
    }
  }

  /**
   * Verify payment status with backend
   */
  async verifyPaymentStatus(paymentId: string): Promise<PaymentStatus> {
    try {
      if (!this.authToken) {
        throw new Error('Authentication required');
      }

      const response = await fetch(`${this.baseUrl}/api/payment/verify/${paymentId}`, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${this.authToken}`,
        },
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || `HTTP ${response.status}: Failed to verify payment`);
      }

      const result = await response.json();

      if (!result.success || !result.data) {
        throw new Error('Invalid response format');
      }

      return result.data;
    } catch (error) {
      throw new Error(
        `Failed to verify payment: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Get order status by order number
   * Requires either auth token (for logged-in users) or email (for guests)
   */
  async getOrderStatusByNumber(
    orderNumber: string,
    guestEmail?: string
  ): Promise<{ orderNumber: string; status: string; mpCollectionStatus?: string }> {
    try {
      const params = guestEmail ? `?email=${encodeURIComponent(guestEmail)}` : '';
      const headers: Record<string, string> = {};
      if (this.authToken) {
        headers['Authorization'] = `Bearer ${this.authToken}`;
      }

      const response = await fetch(
        `${this.baseUrl}/api/payment/order-status/${orderNumber}${params}`,
        {
          method: 'GET',
          headers,
        }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          errorData.message || `HTTP ${response.status}: Failed to fetch order status`
        );
      }

      const result = await response.json();

      if (!result.success || !result.data) {
        throw new Error('Invalid response format');
      }

      return result.data;
    } catch (error) {
      throw new Error(
        `Failed to fetch order status: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Get user orders
   */
  async getUserOrders(page: number = 1, pageSize: number = 10, status?: string): Promise<any> {
    try {
      if (!this.authToken) {
        throw new Error('Authentication required');
      }

      const params = new URLSearchParams({
        page: page.toString(),
        pageSize: pageSize.toString(),
        ...(status && { status }),
      });

      const response = await fetch(`${this.baseUrl}/api/payment/orders?${params}`, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${this.authToken}`,
        },
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || `HTTP ${response.status}: Failed to fetch orders`);
      }

      const result = await response.json();

      if (!result.success) {
        throw new Error('Failed to fetch orders');
      }

      return result.data;
    } catch (error) {
      throw new Error(
        `Failed to fetch orders: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Get specific order details
   */
  async getOrder(orderId: string): Promise<any> {
    try {
      if (!this.authToken) {
        throw new Error('Authentication required');
      }

      const response = await fetch(`${this.baseUrl}/api/payment/orders/${orderId}`, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${this.authToken}`,
        },
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || `HTTP ${response.status}: Failed to fetch order`);
      }

      const result = await response.json();

      if (!result.success || !result.data) {
        throw new Error('Invalid response format');
      }

      return result.data;
    } catch (error) {
      throw new Error(
        `Failed to fetch order: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Request refund for an order
   */
  async requestRefund(orderId: string, reason?: string): Promise<any> {
    try {
      if (!this.authToken) {
        throw new Error('Authentication required');
      }

      const response = await fetch(`${this.baseUrl}/api/payment/refund`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.authToken}`,
        },
        body: JSON.stringify({ orderId, reason }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || `HTTP ${response.status}: Failed to process refund`);
      }

      const result = await response.json();

      if (!result.success || !result.data) {
        throw new Error('Invalid response format');
      }

      return result.data;
    } catch (error) {
      throw new Error(
        `Failed to process refund: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Validate order data before processing
   */
  validateOrderData(orderData: OrderData): string[] {
    const errors: string[] = [];

    // Required fields validation
    if (!orderData.items || orderData.items.length === 0) {
      errors.push('El pedido debe contener al menos un artículo');
    }

    if (!orderData.user?.email) {
      errors.push('El email del usuario es requerido');
    }

    // Only require address for delivery, not for store pickup
    if (orderData.shippingMethod === 'delivery' && !orderData.shippingAddress?.addressLine1) {
      errors.push('La dirección de envío es requerida');
    }

    if (!orderData.total || orderData.total <= 0) {
      errors.push('Total del pedido inválido');
    }

    // Email validation
    if (orderData.user?.email) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(orderData.user.email)) {
        errors.push('Formato de email inválido');
      }
    }

    // Items validation
    orderData.items?.forEach((item, index) => {
      if (!item.productId) {
        errors.push(`Artículo ${index + 1}: ID del producto es requerido`);
      }
      if (!item.quantity || item.quantity <= 0) {
        errors.push(`Artículo ${index + 1}: Cantidad válida es requerida`);
      }
      if (!item.price || item.price <= 0) {
        errors.push(`Artículo ${index + 1}: Precio válido es requerido`);
      }
    });

    return errors;
  }

  /**
   * Get user-friendly status message
   */
  getStatusMessage(status: string): string {
    const messages: Record<string, string> = {
      CREATED: 'Pedido creado',
      PAYMENT_PENDING: 'Esperando pago',
      PAID: 'Pago confirmado',
      PROCESSING: 'Procesando pedido',
      SHIPPED: 'Pedido enviado',
      DELIVERED: 'Pedido entregado',
      CANCELLED: 'Pedido cancelado',
      REFUNDED: 'Pedido reembolsado',
    };

    return messages[status] || 'Estado desconocido';
  }
}

// Export singleton instance
export const mercadoPagoService = new MercadoPagoService();
export default mercadoPagoService;
